const projects = [
  {
    id: "olive-adventure",
    name: "Olive Adventure",
    subtitle: "Top Down Twin-Stick Shooter",
    thumbnailUrl: "images/olive-adventure-banner.png",
    videoFile: "images/olive_adventure.mp4",
    youtubeId: "VIDEO_ID_1",
    galleryImages: ["", ""],
    description: "Detailed description of Project 1...",
    skills: ["Skill 1", "Skill 2", "Skill 3"],
    myRole: "Description of your role in Project 1...",
    hurdles: "Challenges faced and overcome in Project 1...",
    results: "Outcomes and retrospective of Project 1...",
    type: "personal",
  },
  {
    id: "castle-climber-redux",
    name: "Castle Climber REDUX",
    subtitle: "Physics-based 2.5D Platformer",
    thumbnailUrl: "images/ccr-banner.png",
    youtubeId: "VIDEO_ID_2",
    description: "Detailed description of Project 2...",
    skills: ["Skill 4", "Skill 5", "Skill 6"],
    myRole: "Description of your role in Project 2...",
    hurdles: "Challenges faced and overcome in Project 2...",
    results: "Outcomes and retrospective of Project 2...",
    type: "academic",
  },
  {
    id: "draculad",
    name: "Draculad",
    subtitle: "Classically-styled 2D Platformer",
    thumbnailUrl: "images/draculad-banner.png",
    youtubeId: "VIDEO_ID_2",
    description: "Detailed description of Project 2...",
    skills: ["Skill 4", "Skill 5", "Skill 6"],
    myRole: "Description of your role in Project 2...",
    hurdles: "Challenges faced and overcome in Project 2...",
    results: "Outcomes and retrospective of Project 2...",
    type: "personal",
  },
  {
    id: "big-time-crimpark",
    name: "Big Time Crimepark",
    subtitle: "Isometric Mystery Point & Click Adventure",
    thumbnailUrl: "images/crimepark-banner.png",
    youtubeId: "VIDEO_ID_2",
    description: "Detailed description of Project 2...",
    skills: ["Skill 4", "Skill 5", "Skill 6"],
    myRole: "Description of your role in Project 2...",
    hurdles: "Challenges faced and overcome in Project 2...",
    results: "Outcomes and retrospective of Project 2...",
    type: "personal",
  },
  {
    id: "castle-climber",
    name: "Castle Climber",
    subtitle: "Physics-based 2.5D Platformer",
    thumbnailUrl: "images/castle-climber-banner.png",
    youtubeId: "VIDEO_ID_2",
    description: "Detailed description of Project 2...",
    skills: ["Skill 4", "Skill 5", "Skill 6"],
    myRole: "Description of your role in Project 2...",
    hurdles: "Challenges faced and overcome in Project 2...",
    results: "Outcomes and retrospective of Project 2...",
    type: "academic",
  },
  {
    id: "shattered-soul",
    name: "Shattered Soul",
    subtitle: "Classic 2D Platformer",
    thumbnailUrl: "images/shattered-soul-banner.png",
    youtubeId: "VIDEO_ID_2",
    description: "Detailed description of Project 2...",
    skills: ["Skill 4", "Skill 5", "Skill 6"],
    myRole: "Description of your role in Project 2...",
    hurdles: "Challenges faced and overcome in Project 2...",
    results: "Outcomes and retrospective of Project 2...",
    type: "academic",
  },
  // Add more projects as needed
];
